### ISSUE TITLE
NDAInit and malloc...

### ISSUE THREAD

**Issue by ksherlock** [jeremysrand/Listener#3]
I noticed `NDAClose()` (by way of `NDAInit`) was sometimes trying to close an invalid window.  It turns out that the compiler-generated glue code calls `~DAID` before calling your `NDAInit`.  When starting up, it generates a new User ID for mallocs.  When shutting down, it disposes that ID (effectively free()-ing everything that's been malloced). This happens before NDAInit is called.

The main issue though is that NDAInit(0) can be called multiple times without an intervening NDAInit($ffff) and the globals variable isn't nulled out unless globals->ndaActive is true, so there's dangling memory.   If someone else happens to NewHandle it and starts writing data into it, `NDAInit()`/`NDAClose()` will try to close something that isn't a window which can crash hard.

https://github.com/byteworksinc/SysLib/blob/4ff5bdbc7ceb0f46e6756d2dd4f3efc730de4f1b/cd.asm#L506-L571

https://github.com/jeremysrand/Listener/blob/0071f3d4ebfe11e4dc347b3bb7c070842e5aa957/Listener/main.c#L237C1-L254C2

**Comment by jeremysrand** [comment]
I think my latest commit should address the problem.  I have decided to move all memory allocation/deallocation to the NDAOpen() and NDAClose() routines.  The only thing I am doing in NDAInit() is save the userid now.

Does this look good to you?  Any feedback greatly appreciated.  If this is good, I will issue a v1.0.1 update.  Thanks!

**Comment by ksherlock** [comment]
That looks good to me.  Thanks!
